Fix blerpc generator for message
AURA-Devices/blerpc-android pull request #4
Opened 2021-06-04 04:30 UTC by vadim-aura

2021-06-11 13:36 UTC, Nikolas-LFDesigns requested changes

2021-06-11 13:36 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
зачем это всё? Просто чекни имя перед тем как заменять

2021-06-11 13:36 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .map(Common::upperCaseFirstLetter)
так подумал, на самом деле uppercase здесь не нужен, мы потом не отличим пакет от префикса никак

В этом случае вся эта конструкция не нужна

2021-06-11 13:36 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/resources/MessageGeneratorTemplate.mustache
> +import AURACommonProto
это чего такое?

2021-06-11 13:47 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .map(Common::upperCaseFirstLetter)
Если не сделать то common будет с маленькой буквы, и мы конфликт типов получим)

2021-06-11 13:47 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/resources/MessageGeneratorTemplate.mustache
> +import AURACommonProto
Это библиотека наша в проекте где эти классы находятся)

2021-06-11 13:48 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
Не понял, что ты имеешь ввиду)

2021-06-11 13:51 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .map(Common::upperCaseFirstLetter)
Напиши плиз таску и описание мр дополни, чтобы в таком случае было, на что опираться при ревью

2021-06-11 14:06 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
эта проверка здесь исключительно ради избежания двойных подчеркиваний, я же предлагаю сделать ее по месту применения, т.е. выше, и не мучать целый стриминг-массив

2021-06-11 14:07 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/resources/MessageGeneratorTemplate.mustache
> +import AURACommonProto
а почему оно раньше не влияло?

2021-06-15 10:52 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
Посмотрел на состав, мы по старому алгоритму должны получать нечто такое поэтапно:
имеем
`.aura.device.common.BioimpedanceMeasuringScheme`
удаляем `aura.device`, получаем
`..common.BioimpedanceMeasuringScheme`
удаляем точки, получаем
`commonBioimpedanceMeasuringScheme`
Тут кажется все верно тогда портировано, единственно, не делай замену на `_` перед этим (и сплить по точке сразу), у тебя и так прекрасно этим символом происходит join.. И вынеси из стрима uppercase, он нужен только вначале строки, а значит применим ко всей строке, а не ко всем элементам разбитого split-ом массива

2021-06-15 10:52 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
String::isEmpty?

2021-06-15 10:57 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
...common.BioimpedanceMeasuringScheme получаем полностью тип данных Aura_Device_commonBioimpedanceMeasuringScheme, а нам надо Aura_Device_Common_BioimpedanceMeasuringScheme

2021-06-15 10:58 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/resources/MessageGeneratorTemplate.mustache
> +import AURACommonProto
Потому что у нас не было общих типов данных

2021-06-15 10:59 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
Там вроде нельзя сделать отрицание или надо попробовать

2021-06-15 11:01 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
ах да, отрицание же.. ну тут есть guava, у нее есть предикат "not" ;)

2021-06-15 11:02 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/resources/MessageGeneratorTemplate.mustache
> +import AURACommonProto
Т.е. это предзнание, которое мы на генерации закладываем в абсолютно каждый прото? Как-то нехорошо получается. Есть варианты обойти?

2021-06-15 11:04 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
А откуда взялись три точки? И да, мы в этом фрагменте меняем только подпакет_имя, откуда у тебя берется всё остальное?

2021-06-15 11:25 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
(1).aura.device(2).common(3).BioimpedanceMeasuringScheme

Я про финальный результат уже говорю что получится)

2021-06-15 11:26 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/resources/MessageGeneratorTemplate.mustache
> +import AURACommonProto
Тут вариантов нет обойти это внешняя библиотека для генератора с типами данных

2021-06-15 11:26 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
Вон оно что) Узнал новое)

2021-06-15 11:34 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
И все равно это 2 точки, а у тебя в начале 3 ;)  
Мы разбираемся с конкретным фрагментом, он, в твоем случае, если ты мне всё правильно изложил, должен начаться с common_, вот здесь и нужно сделать uppercaseFirstLetter уже после начальной обработки

2021-06-15 11:35 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/resources/MessageGeneratorTemplate.mustache
> +import AURACommonProto
Ну наверняка можно составить список зависимостей и их раскидать сюда? Потому что сегодня common, завтра AuraDevice, послезавтра еще под сотню таких, и что, каждый раз добавлять?

2021-06-16 01:48 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/resources/MessageGeneratorTemplate.mustache
> +import AURACommonProto
Это не зависит от прото файла вообще ни как, поэтому тут ни как не получится обыграть в файле темплейта

2021-06-16 02:17 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
Дак так не получится потому что а если имя типа данных не просто common.Type  а  common.different.TypeName

2021-06-16 02:22 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
Сплитить все равно так надо и всю эту цепочку надо, только можно сплитить сразу по точкам без замены в самом начале

2021-06-16 02:43 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
Что-то я не нашел в guava notEmpty

2021-06-16 11:37 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
> Дак так не получится потому что а если имя типа данных с точек начинается
поясни здесь, я так понимаю, свифтовые типы не могут начинаться с точки

> Сплитить все равно так надо и всю эту цепочку надо, только можно сплитить сразу по точкам без замены в самом начале
кажется, ровно так я и предложил: убери замену, сделай ее с помощью join ;)

И все еще жду описания кейсов, какие имена здесь могут быть и что вообще происходит с этими заглавными буквами

2021-06-16 11:40 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/resources/MessageGeneratorTemplate.mustache
> +import AURACommonProto
Ну если мы знаем карту зависимостей, мы можем сюда поставить не жестко AuraDeviceCommon, а темплейт-переменную, в которую мы бы эту карту подставили, так можно обыграть в темплейте

2021-06-16 11:43 UTC, Nikolas-LFDesigns commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
А, всё верно, на not мы так и не нашли хорошего решения.. ну ок, остаемся как есть

2021-06-17 03:00 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/resources/MessageGeneratorTemplate.mustache
> +import AURACommonProto
Эм карту зависимостей увы как раз мы и не знаем так как в самом файле прото нет зависимостей указывающих на нашу библиотеку для этого делается допконфиг (asciipb) для прото файла) Если бы мы знали то да другое дело, можно было бы как-то обыграть эту ситуацию)

2021-06-17 03:09 UTC, vadim-aura commented on swift-reactive-blerpc/src/main/java/com/blerpc/ios/MessageGenerator.java
> +                .filter(item -> !item.isEmpty())
У нас парсер возвращает такой тип данных `.aura.device.common.BioimpedanceMeasuringScheme` - это не тип данных swift а строка с названием типа, если мы удаляем имя пакета остается `..common.BioimpedanceMeasuringScheme`, если мы начнем сразу у типа данных делать upperCaseFirstLetter тогда это будет точка, а если мы удалим все точки будет `commonBioimpedanceMeasuringScheme` тогда мы сможем сделать upperCaseFirstLetter, но тогда мы опускаем подчеркивание после `common` и тогда будет опять некорректный тип, а нам нужно из всего этого получить `Сommon_BioimpedanceMeasuringScheme`, а позже еще добавится имя пакета и тогда получится `Aura_Device_Сommon_BioimpedanceMeasuringScheme` <= такой результат нам нужен на выходе

2021-06-17 11:58 UTC, evgzor approved these changes

2021-06-17 13:18 UTC, Nikolas-LFDesigns approved these changes

2021-06-17 13:22 UTC, Nikolas-LFDesigns approved these changes

2021-06-17 13:22 UTC, merged